apiVersion: v2
name: infra
description: Infrastructure dependencies for Masaic Platform
version: 0.1.0

# List dependencies
dependencies:
  - name: qdrant
    version: 1.14.1
    repository: https://qdrant.to/helm
  - name: community-operator
    version: 0.13.0
    repository: https://mongodb.github.io/helm-charts
  - name: signoz
    version: 0.86.0
    repository: https://charts.signoz.io
