{{- if .Values.platformui.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platformui.serviceAccountName" . }}
  labels:
    {{- include "platformui.labels" . | nindent 4 }}
  {{- with .Values.platformui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.platformui.serviceAccount.automount }}
{{- end }}
