{{- if .Values.openResponses.mongoDb.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-password
  labels:
    {{- include "platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.openResponses.mongoDb.secrets.adminPassword | quote }}
{{- end }} 