{{- if .Values.openResponses.mongoDb.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-password
type: Opaque
stringData:
  password: {{ .Values.openResponses.mongoDb.secrets.adminPassword | quote }}
{{- end }}
