{{- if .Values.openResponses.qdrant.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: qdrant
type: Opaque
stringData:
  apiKey: {{ .Values.openResponses.qdrant.apikey | quote }}
{{- end }}
