apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.openResponses.service.port }}
      targetPort: 6644
      protocol: TCP
      name: http
  selector:
    {{- include "platform.selectorLabels" . | nindent 4 }}
