{{- if .Values.mongoDb.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-password
type: Opaque
stringData:
  password: {{ .Values.mongoDb.secrets.adminPassword | quote }}
{{- end }} 